### ISSUE TITLE
Use value names which aren’t tied to UI affordance for FedCM parameter: mode

### ISSUE THREAD

**Issue by tttzach** [w3c-fedid/button-mode#5]
We are proposing to rename the values that the `mode` parameter takes from `button` and `widget` to `active` and `passive` respectively.

```javascript
await navigator.credentials.get({
  identity: {
    providers: [{
      // ...
    }],
    mode: "active" // defaults to "passive"
  }
});
```
The reasoning behind this is we feel the names `button` and `widget` are too tied to browser UI implementation whereas  `active` and `passive` better represent the behavior of the FedCM API when these modes are specified.

- `active` implies getting the user to login more actively and if they are currently logged out, we would show a more prominent UI gated behind user activation.
- `passive` implies getting the user to login more passively and if they are currently logged out, we wouldn’t show any UI (modulo the login status API). This is the default value.

This parameter can also be extended to include other modes, if needed. We are open to hearing any and all thoughts.

**Comment by timcappalli** [comment]
Let's discuss at TPAC during the harmonization breakout session: https://github.com/w3c/tpac2024-breakouts/issues/49

**Comment by samuelgoto** [comment]
We discussed this issue in the last CG call and got no objections to rename `mode=button/widget` to `mode=active/passive`.

I'm going to rename this repo and the rest of the documentation as a result. Chrome is going to start to implement this change too.

> Let's discuss at TPAC during the harmonization breakout session: https://github.com/w3c/tpac2024-breakouts/issues/49

I tried to write down @bvandersloot-mozilla 's argument here #6, so that I can close this issue with the convergence that we got at the CG meeting to rename from `button/widget` to `active/passive` mode, and we can follow up on the TPAC harmonization session and #6 separately.

Closing, let me know if there is something that I failed to capture.
